language: php

php:
  - 7.1
#  - 7.2

before_script:
  - composer install

script:
  - vendor/bin/phpcs --standard=vendor/codeigniter4/codeigniter4-standard/CodeIgniter4 .
#  - php vendor/bin/phpunit -v
