language: php

php:
  - 7.1
  - 7.2

before_script:
  - composer install

script:
  - phpcs --standard=vendor/codeigniter4/codeigniter4-standard/CodeIgniter4/ruleset.xml .
  - php vendor/bin/phpunit -v
